import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Box from '@mui/material/Box'
import TextField from '@mui/material/TextField'
import Button from '@mui/material/Button'
import Typography from '@mui/material/Typography'
import Copyright from '@/components/Copyright'
import Alert from '@mui/material/Alert'
import { useState } from 'react'

export default function Home() {

  const [message, setMessage] = useState('');

  const handleSubmit = async (event) => {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    /* console.log({
      email: data.get('email'),
      password: data.get('password'),
    }); */
    if (data.get('password') !== data.get('password2')) {
      setMessage("Las contraseñas no coinciden");
      return;
    }
   
    const response = await fetch('/api/auth/register', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        email: data.get('email'),
        password: data.get('password'),
      }),
    });
    if (response.ok) {
      Router.push('/');     
    } else {
      switch (response.status) {
        case 401:
          setMessage("El Email ya se encuentra registrado");
          break;
        case 500:
          setMessage("Error interno del servidor");
          break;
        case 400:
          setMessage("Se deben completar todos los campos");
          break;
        default:
          break;
      }
    }
  };

  const inputClick = () => {
    setMessage('');
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Box
          component="form"
          onSubmit={handleSubmit}
          sx={{
            display: 'flex',
            flexDirection: 'column',
            '& > :not(style)': { m: 1, minWidth: 300},
            alignItems: 'center',
          }}
          validate
          autoComplete="off"
        >
          <Typography component="h1" variant="h5" 
            sx={{
              textAlign: 'center',
            }}
          >
            Registro de usuario
          </Typography>
          <TextField
            required
            id="email"
            name='email'
            label="Email"
            type="text"
            onFocus={inputClick}
          />
          <TextField
            required
            id="password"
            name='password'
            label="Contraseña"
            type="password"
            onFocus={inputClick}
            autoComplete="current-password"
          />
          <TextField
            required
            id="password2"
            name='password2'
            label="Repetir contraseña"
            type="password"
            onFocus={inputClick}
          />
          {message && <Alert severity="error">{message}</Alert>}
          <Button
              type="submit"
              variant="contained"
              sx={{ mt: 3, mb: 2 }}
            >
              Registrarme
          </Button>
        </Box>
  
        <Copyright sx={{ mt: 8, mb: 4 }} />
      </main>
    </>
  )
}
